project/app01/urls.py
from django.urls import path, include
from django.views.generic import TemplateView
from app01.views import ParentListView, ParentDetailView

urlpatterns = [
    path('', TemplateView.as_view(template_name="index.html"), name="home"),
    path('parents', ParentListView.as_view(), name="parents"),
    path('<int:pk>', ParentDetailView.as_view(), name="parent"),
]

project/project/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

project/app01/models.py
from django.db import models

class Parent(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)

    def __str__(self):
        return self.first_name + " " + self.last_name

class Child(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    parent = models.ForeignKey(Parent, on_delete=models.CASCADE)

    def __str__(self):
        return self.first_name + " " + self.last_name

project/app01/views.py
from django.shortcuts import render
from app01.models import Parent
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView

class ParentListView(ListView):
    model = Parent

class ParentDetailView(DetailView):
    model = Parent

project/app01/templates/app01/parent_detail.html
{% extends "base.html" %}

{% block title%}{{object}}{% endblock %}

{% block body %}

  {% for children in object.child_set.all %}
    <p>{{ children }}</p>
  {% endfor %}

{% endblock %}

project/app01/templates/app01/parent_list.html
{% extends "base.html" %}

{% block title%} Parents {% endblock %}

{% block body%}
<ul>
  {% for parent in object_list %}
    <li> <a href="{% url "parent" parent.id %}">{{parent}}</a> </li>
    {% empty %}
    <li>No parents</li>
  {% endfor %}
</ul>
{% endblock %}

project/app01/templates/base.html
<!doctype html>

<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Django Practice test</title>
</head>

<body>
  <h1<a href="{% url "home" %}">Django Practice Project</a></h1>
    <p><a href="{% url "parents" %}">Parents</a></p>
  <h2>{% block title %}{% endblock %}</h2>

  {% block body %}
  {% endblock %}
</body>
</html>

project/app01/templates/index.html
{% extends "base.html" %}
{% block title %}Home{% endblock %}

{% block body %}
<p>Site created to better understand django.</p>
{% endblock %}